[package]
name = "genetic"
version = "0.1.0"
authors = ["Daniel Bider <bider.daniel@gmail.com>"]

[dependencies]
rand = "*"
pbr = "1.0.0"
gnuplot = "*"
serde_json = "*"

[[bin]]
name = "genetic"
path = "./src/main.rs"