[package]
name = "genetic"
version = "0.1.0"
authors = ["Daniel Bider <bider.daniel@gmail.com>"]

[dependencies]
uuid = { version = "*", features = ["v4"] }
rand = "*"
pbr = "1.0.0"

[[bin]]
name = "genetic"
path = "./src/main.rs"