---
evolution_params: 
  generations: 1000
  population_count: 100
  mutation_rate: 0.05
  crossover_rate: 0.85
  tournament_size: 2
dataset_path: ""
log_results: true
log_directory: logs/
version: 0.1.0
